#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Usage: $0 <commit_message>"
    exit 1
fi
commit_message="${@:2}"
git add .
git commit -m "$commit_message"
git pull
git push
if [ $? -eq 0 ]; then
    echo "Git commands executed successfully."
else
    echo "An error occurred during Git operations."
fi
