CC = gcc
CFLAGS = -Wall -Wextra -pthread
LDFLAGS = -lm

CLIENT_SOURCES = socketAPI.c client.c
NMS_SOURCES = socketAPI.c nms.c trie.c stack.c logging.c
SS_SOURCES = ss.c trie.c seek.c socketAPI.c stack.c

CLIENT_EXECUTABLE = client
NMS_EXECUTABLE = nms
SS_EXECUTABLE=ss

all: $(CLIENT_EXECUTABLE) $(NMS_EXECUTABLE) $(SS_EXECUTABLE)

$(CLIENT_EXECUTABLE): $(CLIENT_SOURCES)
	$(CC) $(CFLAGS) $(CLIENT_SOURCES) -o $(CLIENT_EXECUTABLE) $(LDFLAGS)

$(NMS_EXECUTABLE): $(NMS_SOURCES)
	$(CC) $(CFLAGS) $(NMS_SOURCES) -o $(NMS_EXECUTABLE) $(LDFLAGS)

$(SS_EXECUTABLE): $(SS_SOURCES)
	$(CC) $(CFLAGS) $(SS_SOURCES) -o $(SS_EXECUTABLE) $(LDFLAGS)

clean:
	rm -f $(CLIENT_EXECUTABLE) $(NMS_EXECUTABLE) $(SS_EXECUTABLE)